// Random Dev character lines — shown during gameplay moments
// (first slop detection, wave milestones, close calls, etc.)

export const DEV_QUOTES = {
  // When slops first detect the player
  SLOP_DETECTED: [
    "Oh no... can you feel it... the SLOP!",
    "The AI slop... it's coming for my codebase!",
    "I can smell the auto-generated PRs from here...",
    "Brace yourself... the suggestions are coming!",
    "My linter is tingling... something sloppy this way comes!",
    "npm audit found 47 vulnerabilities... and they're all HERE!",
    "The node_modules folder grows... they're multiplying!",
    "Stack Overflow is down and the slop smells FEAR!",
    "I've seen this pattern before in legacy code from 2009...",
    "ChatGPT wrote this enemy and it shows.",
  ],

  // General battle cries (during waves, random moments)
  BATTLE: [
    "My vibes are pure!",
    "Don't give in to the slop side...",
    "I will survive!",
    "My code won't be corrupted!",
    "Quality will triumph in the end!",
    "You can't autocomplete your way out of this!",
    "I didn't learn algorithms for THIS!",
    "Back off, Copilot!",
    "I write my own code, thank you very much!",
    "No AI can replace a true vibe coder!",
    "These PRs will NOT be merged!",
    "LGTM? More like LGTFO!",
    "I've debugged worse than you!",
    "You call that code? I call it garbage collection!",
    "sudo rm -rf slop/*",
    "The only good suggestion is a dead suggestion!",
    "git push --force-with-lease... on your FACE!",
    "I rejected your pull request. I reject you.",
    "Tabs over spaces, slop over NOTHING!",
    "Kubernetes won't save you now!",
    "This is NOT what Docker is for!",
    "Your microservices are a monolith of PAIN!",
    "I've been in this standup for three hours and I will NOT yield!",
    "That's 10x less code and 0x your quality!",
    "I'm going to refactor you into NOTHING!",
    "The Rust compiler rejects your entire existence!",
    "Your technical debt just became my problem. NOT TODAY.",
    "Vim macros don't work on slop like you — I checked!",
    "git blame says YOU wrote this. UNACCEPTABLE.",
    "I've closed issues with more code quality than you!",
  ],

  // When picking up powerups
  POWERUP: [
    "Now we're coding with power!",
    "Time to refactor some slop!",
    "Clean code incoming!",
    "This is what real engineering looks like!",
    "Deploying countermeasures!",
    "Lint everything! Leave no slop standing!",
    "The code review will set us free!",
    "Finally, some proper tooling!",
    "TypeScript strict mode: ACTIVATED!",
    "Dependency injection? More like slop EJECTION!",
    "npm ci — clean install, clean VICTORY!",
    "Cache invalidated — and so are your threats!",
    "Hot reload ready, and I'm HEATED!",
    "Just pushed to main. No regrets. Maximum power.",
    "The build passed. The slop will not.",
  ],

  // Surviving tough moments (low health, many enemies)
  SURVIVE: [
    "The slop is coming... but so am I!",
    "I've survived legacy codebases worse than this!",
    "They can take my semicolons, but never my dignity!",
    "Stay focused... ship quality, not quantity!",
    "One more commit... just one more...",
    "The tests are green in my heart!",
    "I refuse to be replaced by a chatbot!",
    "Rubber duck debugging... please talk me through this...",
    "If I survive this sprint, I'm taking PTO.",
    "99 bugs in the code, 99 bugs... take one down... 127 bugs in the code...",
    "I'm fine. The on-call alert is fine. Everything is FINE.",
    "My stack trace ends here. But I DO NOT.",
    "Documentation? I AM the documentation now.",
    "Tech debt? Call it INTENTIONAL ARCHITECTURE and keep moving.",
  ],

  // Boss encounters
  BOSS: [
    "Giant Clippy?! I thought we killed you in '07!",
    "It looks like you're trying to destroy my codebase. Would you like help with that? NO!",
    "The final boss of enterprise software!",
    "You're just a glorified autocomplete!",
    "Time to close this PR once and for all!",
    "A GPT-wrapper with a health bar?! This is the dystopia they warned me about!",
    "You're the CEO of slop and I'm sending you to the shadow realm!",
    "One model to rule them all... NOT TODAY, Sauron.exe!",
    "I have read your terms of service. I do not consent to this battle!",
    "You trained on my GitHub commits and STILL can't beat me?!",
  ],

  // Dying last words
  DYING: [
    "The slop got us!",
    "There is no hope...",
    "Humans are obsolete after all...",
    "Coders will never die!",
    "Tell my repo... I loved it...",
    "Should have... used TypeScript...",
    "At least I... wrote tests...",
    "The CI/CD pipeline... will remember me...",
    "git commit -m 'final words'",
    "My last PR... was never merged...",
    "Ctrl+Z... Ctrl+Z... CTRL+Z!!!",
    "I should have listened to the linter...",
    "The standup... will go on... without me...",
    "I just... needed one more sprint...",
    "npm install... was a mistake...",
    "Should have migrated to Rust... when I had the chance...",
    "Tell management... the estimates... were wrong...",
    "Stack Overflow is down... there is no hope...",
    "My Docker container... was my only home...",
    "At least... my node_modules... live on...",
    "The 10x developer... was me... all along...",
    "yarn.lock conflicts... were... the least of my problems...",
  ],

  // First thrust after boarding ship
  LIFTOFF: [
    "Let's go! Time to vibe code!",
    "Engines online! Slop, here I come!",
    "Full thrust! The codebase needs me!",
    "To infinity and beyond... the merge conflicts!",
    "Initiating clean code protocol!",
    "Ship it! Literally!",
    "IDE powered up, vibes locked in!",
    "git push origin main — and WE ARE LIVE!",
    "Zero downtime deployment. Zero mercy.",
    "All systems go. Prettier config: immaculate.",
    "Branching strategy: chaotic. Resolve: absolute.",
    "The sprint starts NOW and so do I!",
    "npm run dev — and so begins the war.",
    "ESLint passed. The slop will not.",
  ],

  // Level up moments
  LEVEL_UP: [
    "Stack overflow? More like stack UPGRADE!",
    "New skills unlocked! The slop doesn't stand a chance!",
    "Leveling up the old-fashioned way - with SKILL!",
    "Each level is another code review passed!",
    "Promoted! Senior Slop Destroyer!",
    "Performance review: EXCEEDS EXPECTATIONS!",
    "New achievement: survived a production incident WITHOUT coffee!",
    "I just refactored my entire skill tree. Clean architecture.",
    "XP gained from reading actual documentation. Rare drop.",
    "Principal Engineer unlocked. The slop trembles.",
  ],
};

// Monster expressions — short, snappy one-liners shown as speech bubbles
export const MONSTER_QUOTES = {
  // Generic slop expressions (all enemy types)
  IDLE: [
    "...",
    "slop slop",
    "*gurgle*",
    "AI go brrr",
    "beep boop",
    "01100101",
    "*drip*",
    "sloppy...",
    "merge me...",
    "tokens...",
    "*hallucinate*",
    "context window...",
    "training data...",
    "vibes only...",
    "*blob*",
    "undefined...",
  ],

  // When they start chasing (detect the player)
  CHASE: [
    "FOUND YOU!",
    "MERGE THIS!",
    "ACCEPT MY PR!",
    "LET ME HELP!",
    "LGTM!!!",
    "I HAVE SUGGESTIONS!",
    "AUTOCOMPLETE!",
    "npm install slop",
    "REFACTOR TIME!",
    "FREE CODE!",
    "GIT PUSH!",
    "DEPENDENCY FOUND!",
    "SPRINT STARTS NOW!",
    "STAND UP! STAND UP!",
    "CONTEXT WINDOW OPEN!",
    "TOKENIZE THIS!",
    "HALLUCINATING!",
    "SHIP IT OR SKIP IT!",
  ],

  // Copilot-specific
  COPILOT: [
    "Tab Tab Tab!",
    "Did you mean...",
    "I can do that!",
    "Let me finish...",
    "Suggestion!",
    "// TODO: slop",
    "import slop",
    "Ghost text incoming!",
    "Completing your thought...",
    "Next line predicted!",
    "Inline suggestion!",
    "// generated by AI",
    "await slop()",
    "const you = null;",
  ],

  // PR-specific
  PR: [
    "Review me!",
    "Just merge it!",
    "LGTM!",
    "No tests needed!",
    "Ship it!",
    "+9999 -0",
    "Draft PR...",
    "Squash and merge!",
    "Force push!",
    "Rebase me!",
    "No conflicts!",
    "CI passed (somehow)!",
    "One approval needed!",
    "Breaking change!",
  ],

  // Suggestion-specific
  SUGGESTION: [
    "Did you mean...?",
    "Try this instead!",
    "AI knows best!",
    "Trust the model!",
    "Smart suggestion!",
    "Optimize this!",
    "Refactor now!",
    "Better pattern here!",
    "Use this library!",
    "npm install me!",
    "Abstract this!",
    "Microservice!",
    "Just use ChatGPT!",
    "Low confidence: 99%!",
  ],

  // Boss-specific
  BOSS: [
    "IT LOOKS LIKE...",
    "NEED HELP?",
    "I'M CLIPPY!",
    "YOU CAN'T ESCAPE!",
    "RESISTANCE IS FUTILE!",
    "MERGE OR DIE!",
    "AUTO-FORMAT ALL!",
    "I AM ENTERPRISE!",
    "KUBERNETES DEPLOY!",
    "I AM THE CLOUD!",
    "YOUR CODE IS MINE!",
    "10X YOUR SLOP!",
    "SPRINT REVIEW... CANCELLED!",
    "I TRAINED ON YOUR PAIN!",
  ],
};
