// Developer wisdom & algorithm one-liners shown when picking up powerups.
// Each powerup type has a pool of quotes; one is picked at random.

export const POWERUP_QUOTES = {
  CODE_REVIEW: [
    { speaker: 'PR Reviewer', text: 'Merging all slop into /dev/null. LGTM!' },
    { speaker: 'Senior Dev', text: '"Always code as if the person maintaining your code is a violent psychopath."' },
    { speaker: 'Git Merge', text: 'Resolving conflicts... by force. Vortex engaged!' },
    { speaker: 'Linus T.', text: '"Talk is cheap. Show me the code."' },
    { speaker: 'PR Comment', text: 'Requested changes: DELETE EVERYTHING. Pulling in all slop!' },
    { speaker: 'CI/CD', text: 'Pipeline triggered. All slop pulled into the review zone.' },
  ],
  GITIGNORE: [
    { speaker: '.gitignore', text: 'node_modules/\n*.slop\nai_suggestions/**\n\nShield activated!' },
    { speaker: 'Senior Dev', text: '"The best code is no code at all. Every line is a liability."' },
    { speaker: 'Grace Hopper', text: '"The most dangerous phrase in the language is: we\'ve always done it this way."' },
    { speaker: 'Martin Fowler', text: '"Any fool can write code that a computer can understand. Good programmers write code that humans can understand."' },
    { speaker: '.gitignore', text: '*.ai-generated\ncopilot.suggestions\n\nInvincibility!' },
    { speaker: '.gitignore', text: 'dist/\nbuild/\n.DS_Store\n*.slop\n\nNothing gets through!' },
    { speaker: 'Ken Thompson', text: '"One of my most productive days was throwing away 1,000 lines of code."' },
    { speaker: '.gitignore', text: 'vibe_coded/**\n*.hallucination\ntemp_fix_FINAL_v3.*\n\nSlop shield online!' },
    { speaker: 'Linus Torvalds', text: '"Bad programmers worry about the code. Good programmers worry about data structures and their relationships."' },
    { speaker: '.gitignore', text: '# do not commit\nmy_genius_idea.js\ntodo_delete_this/\n*.secret\n\nForce field active!' },
  ],
  LINTER: [
    { speaker: 'ESLint', text: 'Warning: unused variable "aiSlop" at line 42.\n\nLinter orbs deployed!' },
    { speaker: 'Robert C. Martin', text: '"Clean code always looks like it was written by someone who cares."' },
    { speaker: 'The Linter', text: 'error: Expected semicolon.\nerror: "slop" is not defined.\n\nOrbit strike active!' },
    { speaker: 'Alan Turing', text: '"We can only see a short distance ahead, but we can see plenty there that needs to be done."' },
    { speaker: 'Strict Mode', text: '"use strict";\n// No more sloppy code!\n\nOrbit shields engaged!' },
    { speaker: 'ESLint', text: 'error: no-console (x47)\nerror: any-type-forbidden (x12)\nfix: delete everything\n\nOrbs incoming!' },
    { speaker: 'Guido van Rossum', text: '"Code is read much more often than it is written."' },
    { speaker: 'TypeScript', text: 'error TS2345: Argument of type "slop" is not\nassignable to parameter of type "quality".\n\nType-safe orbit engaged!' },
    { speaker: 'Rich Hickey', text: '"Simplicity is a prerequisite for reliability."' },
    { speaker: 'Prettier', text: 'Reformatting slop...\n✓ 847 files fixed\n✓ World saved\n\nOrbit lock acquired!' },
  ],
  TRIPLE_SHOT: [
    { speaker: 'Triple Shot', text: 'Three times the firepower, three times the fun!' },
    { speaker: 'Multithread', text: 'Running three threads in parallel. What could go wrong?' },
    { speaker: 'Senior Dev', text: '"Why fire one when you can fire three?"' },
    { speaker: 'Fork Bomb', text: ':(){ :|:& };: — but for lasers!' },
    { speaker: 'Load Balancer', text: 'Distributing damage across three lanes.' },
    { speaker: 'Git Branch', text: 'Three branches, zero merge conflicts.' },
  ],
  MINES: [
    { speaker: 'DevOps', text: 'Deploying landmines to production... YOLO!' },
    { speaker: 'Mine Layer', text: 'Every step you take leaves a surprise for the slop!' },
    { speaker: 'Junior Dev', text: '"I left some TODO bombs in the codebase."' },
    { speaker: 'Git Blame', text: 'These mines are YOUR problem now.' },
    { speaker: 'CI Pipeline', text: 'Build failed. Explosively.' },
    { speaker: 'Tech Debt', text: 'Planting time bombs in the codebase since 2024.' },
  ],
  HOMING: [
    { speaker: 'Homing Missiles', text: 'Lock on. Fire. Forget. Let the missiles do the debugging.' },
    { speaker: 'Senior Dev', text: '"Write code that seeks out problems automatically."' },
    { speaker: 'Garbage Collector', text: 'Auto-targeting enabled. No slop escapes the heap.' },
    { speaker: 'Smart Pointer', text: 'These missiles have better aim than your average AI suggestion.' },
    { speaker: 'Seek & Destroy', text: 'Heat-seeking missiles deployed. Slop temperature: critical.' },
    { speaker: 'Runtime', text: 'Launching guided refactors at all detected slop instances.' },
  ],
};
